# Generated by Django 4.0.2 on 2022-02-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CroneArBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('rol', models.CharField(choices=[('CQB', 'CQB'), ('ASSAULT', 'ASSAULT'), ('SUPPORT', 'SUPPORT'), ('DMR', 'DMR'), ('SNIPER', 'SNIPER')], max_length=30)),
                ('fps', models.IntegerField()),
                ('upload_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CroneArBack.user')),
            ],
        ),
    ]
